allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
overrides:
  flatted: ">=3.4.2"
  rollup: ">=4.59.0"
  picomatch: ">=4.0.4"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
